import type { ApiBlock, Devgraph, EnvBlock, ServiceBlock } from '../index.js';
import { getLandmarkDescription, type InferredData, mergeCommands } from './inference.js';

export interface AgentTemplateData {
  service: ServiceBlock & { apis?: ApiBlock[]; env?: EnvBlock[] };
  graph: Devgraph;
  inferred: InferredData;
  servicePath?: string;
  bestEffort: boolean;
}

function todoPlaceholder(field: string): string {
  return `<!-- TODO: ${field} -->`;
}

export function renderAgentMarkdown(data: AgentTemplateData): string {
  const { service, graph, inferred, servicePath, bestEffort } = data;
  const lines: string[] = [];
  const timestamp = new Date().toISOString().split('T')[0];

  // Header
  lines.push(`# AGENTS.md - ${service.name}`);
  lines.push('');
  lines.push(`> Auto-generated by DevGraph on ${timestamp}`);
  lines.push('');

  // Overview section
  lines.push('## Overview');
  lines.push('');
  lines.push(`| Property | Value |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Service | **${service.name}** |`);
  lines.push(`| Type | \`${service.type}\` |`);
  if (servicePath) {
    lines.push(`| Path | \`${servicePath}\` |`);
  }
  if (inferred.packageManager) {
    lines.push(`| Package Manager | ${inferred.packageManager} |`);
  }
  lines.push('');

  // Run section (commands)
  const mergedCommands = mergeCommands(service.commands, inferred.commands);
  const commandKeys = ['dev', 'build', 'test', 'start', 'lint'];

  if (Object.keys(mergedCommands).length > 0) {
    lines.push('## Run');
    lines.push('');
    lines.push('```bash');
    for (const key of commandKeys) {
      if (mergedCommands[key]) {
        lines.push(`# ${key}`);
        lines.push(mergedCommands[key]);
        lines.push('');
      }
    }
    // Other commands not in the standard list
    for (const [key, value] of Object.entries(mergedCommands)) {
      if (!commandKeys.includes(key)) {
        lines.push(`# ${key}`);
        lines.push(value);
        lines.push('');
      }
    }
    lines.push('```');
    lines.push('');
  } else if (bestEffort) {
    lines.push('## Run');
    lines.push('');
    lines.push(todoPlaceholder('Add run commands'));
    lines.push('');
  }

  // Dependencies section
  if (service.depends && service.depends.length > 0) {
    lines.push('## Dependencies');
    lines.push('');
    lines.push('This service depends on:');
    lines.push('');
    for (const dep of service.depends) {
      const depService = graph.services[dep];
      if (depService) {
        lines.push(`- **${dep}** (\`${depService.type}\`)`);
      } else {
        lines.push(`- **${dep}** (external)`);
      }
    }
    lines.push('');
  }

  // Interfaces section
  const hasConsumedAPIs = service.depends && service.depends.some((dep) => graph.services[dep]?.apis?.length);
  const hasExposedAPIs = service.apis && service.apis.length > 0;

  if (hasConsumedAPIs || hasExposedAPIs) {
    lines.push('## Interfaces');
    lines.push('');

    // APIs Consumed
    if (hasConsumedAPIs) {
      lines.push('### APIs Consumed');
      lines.push('');
      for (const dep of service.depends ?? []) {
        const depService = graph.services[dep];
        if (depService?.apis && depService.apis.length > 0) {
          lines.push(`**${dep}:**`);
          for (const api of depService.apis) {
            const routes = Object.keys(api.routes || {});
            if (routes.length > 0) {
              lines.push('');
              for (const route of routes) {
                lines.push(`- \`${route}\``);
              }
            }
          }
          // Search terms for finding references
          const envPrefix = dep.toUpperCase().replace(/-/g, '_');
          lines.push('');
          lines.push(`> Search terms: \`${dep}\`, \`${envPrefix}_URL\`, \`${envPrefix}_API_URL\``);
          lines.push('');
        }
      }
    }

    // APIs Exposed
    if (hasExposedAPIs) {
      lines.push('### APIs Exposed');
      lines.push('');
      lines.push('| Method | Path | Description |');
      lines.push('|--------|------|-------------|');
      for (const api of service.apis ?? []) {
        for (const [route, desc] of Object.entries(api.routes || {})) {
          const parts = route.split(' ');
          const method = parts.length > 1 ? parts[0] : 'GET';
          const path = parts.length > 1 ? parts.slice(1).join(' ') : route;
          const description = typeof desc === 'string' && desc ? desc : '-';
          lines.push(`| \`${method}\` | \`${path}\` | ${description} |`);
        }
      }
      lines.push('');
    }
  }

  // Environment section
  if (service.env && service.env.length > 0) {
    lines.push('## Environment');
    lines.push('');
    lines.push('| Variable | Default |');
    lines.push('|----------|---------|');
    for (const env of service.env) {
      for (const [key, val] of Object.entries(env.vars)) {
        lines.push(`| \`${key}\` | \`${val}\` |`);
      }
    }
    lines.push('');
  }

  // Landmarks section
  if (inferred.landmarks.length > 0) {
    lines.push('## Landmarks');
    lines.push('');
    lines.push('Key directories in this service:');
    lines.push('');
    for (const landmark of inferred.landmarks) {
      const desc = getLandmarkDescription(landmark);
      lines.push(`- \`${landmark}/\` - ${desc}`);
    }
    lines.push('');
  }

  // Safety Checks section
  lines.push('## Safety Checks');
  lines.push('');
  lines.push('Before submitting changes, verify:');
  lines.push('');

  if (mergedCommands.test) {
    lines.push(`- [ ] Tests pass: \`${mergedCommands.test}\``);
  } else if (bestEffort) {
    lines.push(`- [ ] Tests pass ${todoPlaceholder('Add test command')}`);
  }

  if (mergedCommands.lint) {
    lines.push(`- [ ] Linting passes: \`${mergedCommands.lint}\``);
  }

  if (mergedCommands.build) {
    lines.push(`- [ ] Build succeeds: \`${mergedCommands.build}\``);
  }

  // Add healthcheck if defined
  if (service.healthcheck) {
    if (service.healthcheck.http) {
      lines.push(`- [ ] Health check passes: \`curl ${service.healthcheck.http}\``);
    } else if (service.healthcheck.tcp) {
      lines.push(`- [ ] Port ${service.healthcheck.tcp} accepting connections`);
    } else if (service.healthcheck.command) {
      lines.push(`- [ ] Health check: \`${service.healthcheck.command}\``);
    }
  }

  lines.push('');

  return lines.join('\n');
}
